_BASE_: "Base-RCNN-VoVNet-FPN.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/rptgw6stppbiw1u/vovnet19_ese_detectron2.pth?dl=1"
  MASK_ON: False
  VOVNET:
    CONV_BODY : "V-19-eSE"
SOLVER:
  STEPS: (3000, 4000)
  MAX_ITER: 5000
OUTPUT_DIR: "checkpoints/FRCN-V2-19-3x"